services:
  nginx:
    image: nginx:alpine
    container_name: global-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - proxy-net
    restart: always

networks:
  proxy-net:
    external: true
