# Dev Environment
server {
    listen 80;
    server_name dev-sapcyti.duckdns.org;

    location / {
        proxy_pass http://sapcyti-dev-edge:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# QA Environment
server {
	listen 80;
	server_name qa.sapcyti.local;

	location / {
		proxy_pass http:sapcyti-qa-edge:80;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

# Prod Environment
server {
	listen 80;
	server_name sapcyti.local;

	location / {
		proxy_pass http://sapcyti-prod-edge:80;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}